version: '3.7'
services:
  postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      # - db-data:/etc/data
      - ./configs/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
      POSTGRES_DB: ${POSTGRES_DB}
    
    # extra_hosts:
      # - "pghost:172.18.0.2"

  frontend:
    image: apache/superset:latest-dev
    ports:
      - "27364:8088"
    restart: always
    depends_on:
      - "postgres"
    volumes:
      - ./configs/entrypoint.sh:/app/superset_home/entrypoint.sh
      # - ./configs/superset_config.py:/app/superset_home/superset_config.py
      - ./configs/superset_config.py:/app/pythonpath/superset_config.py
    command: ["bash","/app/superset_home/entrypoint.sh"]
    #  ["/bin/sh","-c","/app/superset_home/entrypoint.sh"]

    env_file:
    - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
volumes:
  pgdata:
    # driver: flocker
    # driver_opts:
      # size: "10GiB"
